# Generated by Django 3.2.8 on 2021-10-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('member_no', models.AutoField(db_column='member_no', primary_key=True, serialize=False)),
                ('member_id', models.CharField(db_column='member_id', max_length=20)),
                ('member_pwd', models.CharField(db_column='member_pwd', max_length=20)),
                ('member_name', models.CharField(db_column='member_name', max_length=50)),
                ('member_email', models.CharField(db_column='member_email', max_length=50)),
                ('usage_flag', models.CharField(db_column='usage_flag', default='1', max_length=10)),
                ('register_date', models.DateTimeField(db_column='register_date')),
                ('access_latest', models.DateTimeField(db_column='access_latest')),
            ],
            options={
                'db_table': 'member',
                'managed': False,
            },
        ),
    ]
