# Generated by Django 3.2.8 on 2021-10-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='board',
            table='board',
        ),
    ]
